# Generated by Django 4.0.6 on 2022-07-26 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incost', '0002_alter_clients_name_alter_durations_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durations',
            name='mode_id',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-3)]),
        ),
    ]
