# Generated by Django 4.0.6 on 2022-07-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incost', '0003_alter_durations_mode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durations',
            name='mode_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incost.modes'),
        ),
    ]
